ALTER TABLE kris
ADD COLUMN IF NOT EXISTS amber_threshold_min NUMERIC(15,2),
ADD COLUMN IF NOT EXISTS amber_threshold_max NUMERIC(15,2),
ADD COLUMN IF NOT EXISTS is_archived BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS archived_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS archived_reason TEXT DEFAULT '';

CREATE INDEX IF NOT EXISTS idx_kris_is_archived ON kris(is_archived);
