-- Add scheduling config to mitigations (Plan)
ALTER TABLE mitigations ADD COLUMN IF NOT EXISTS report_day INTEGER DEFAULT NULL;
  -- For mingguan: 0=Minggu, 1=Senin, 2=Selasa, 3=Rabu, 4=Kamis, 5=Jumat, 6=Sabtu
ALTER TABLE mitigations ADD COLUMN IF NOT EXISTS report_date INTEGER DEFAULT NULL;
  -- For bulanan: 1-31, For triwulan: 1-31 (tanggal pelaporan di bulan triwulan)

-- Mitigation Tasks (auto-generated by cron / manually)
CREATE TABLE IF NOT EXISTS mitigation_tasks (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    mitigation_id   UUID NOT NULL REFERENCES mitigations(id) ON DELETE CASCADE,
    risk_id         UUID NOT NULL REFERENCES risks(id) ON DELETE CASCADE,
    
    -- Period identification
    period_label    TEXT NOT NULL,                    -- e.g. "Minggu 2, Mar 2026", "Maret 2026", "Q1 2026"
    period_start    DATE NOT NULL,                    -- start of the period
    period_end      DATE NOT NULL,                    -- end of the period
    due_date        DATE NOT NULL,                    -- deadline for this task
    
    -- Progress report (filled by PIC)
    status          TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','done','overdue','skipped')),
    progress_pct    INTEGER DEFAULT 0 CHECK (progress_pct BETWEEN 0 AND 100),
    actual_cost     NUMERIC(15,2) DEFAULT 0,
    evidence_url    TEXT DEFAULT '',
    notes           TEXT DEFAULT '',
    
    -- Who reported
    reported_by     UUID REFERENCES users(id),
    reported_at     TIMESTAMPTZ,
    
    -- Auto-generated metadata
    generated_by    TEXT DEFAULT 'cron' CHECK (generated_by IN ('cron','manual')),
    created_at      TIMESTAMPTZ DEFAULT now(),
    updated_at      TIMESTAMPTZ DEFAULT now()
);

-- Indexes for fast lookups
CREATE INDEX IF NOT EXISTS idx_mitigation_tasks_mitigation ON mitigation_tasks(mitigation_id);
CREATE INDEX IF NOT EXISTS idx_mitigation_tasks_risk ON mitigation_tasks(risk_id);
CREATE INDEX IF NOT EXISTS idx_mitigation_tasks_status ON mitigation_tasks(status);
CREATE INDEX IF NOT EXISTS idx_mitigation_tasks_due_date ON mitigation_tasks(due_date);
CREATE INDEX IF NOT EXISTS idx_mitigation_tasks_reported_by ON mitigation_tasks(reported_by);

-- Prevent duplicate tasks for same mitigation + period
CREATE UNIQUE INDEX IF NOT EXISTS idx_mitigation_tasks_unique_period 
    ON mitigation_tasks(mitigation_id, period_start, period_end);
